site_name: "Warp tutorial"
site_url: "https://massimim.github.io/warp-tutorial/"
repo_url: "https://github.com/massimim/warp-tutorial"
repo_name: "warp-tutorial"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - toc.follow
    - search.highlight
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light-blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light-blue
nav:
  - Home: index.md
#   #- Home: index.md
#   #- Guide: guide.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - tables # Enables standard Markdown tables
  #- pymdownx.tabular # Enables advanced tables -> pip install pymdown-extensions
  - pymdownx.superfences # Required for some advanced formatting
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/custom.css

plugins:
  - search
